services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres_db/weather
      AIRFLOW__WEBSERVER__SECRET_KEY: "6b828ded2baab884feadfa1fcb3527b9a584c3ee74f3896fa6ab9f4a847020a5"  
    entrypoint: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@test.com || true
      "

  airflow-webserver:
    build: .
    container_name: airflow_webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres_db/weather
      AIRFLOW__WEBSERVER__SECRET_KEY: "6b828ded2baab884feadfa1fcb3527b9a584c3ee74f3896fa6ab9f4a847020a5"  
    ports:
      - "8080:8080"
    volumes:
      - ./:/opt/airflow/dags
    command: airflow webserver

  airflow-scheduler:
    build: .
    container_name: airflow_scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres_db/weather
      AIRFLOW__WEBSERVER__SECRET_KEY: "6b828ded2baab884feadfa1fcb3527b9a584c3ee74f3896fa6ab9f4a847020a5"  
    volumes:
      - ./:/opt/airflow/dags
    command: airflow scheduler

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  init-topics:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka1
      - kafka2
    volumes:
      - ./init:/init
    entrypoint: ["/bin/bash", "-c"]
    command: >
     "chmod +x /init/create_topic.sh &&
      echo Waiting for Kafka... &&
      until kafka-topics --list --bootstrap-server kafka1:9092,kafka2:9092; do
      sleep 3;
      done &&
      /init/create_topic.sh"
volumes:
  postgres_data: